# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e07f237856fb8b453cad03ad064168150e29530efc600b4fc3c4804c6f615a2170f5358dae5f5bfdedd60d09f8b7bd97d930d1e6f08c30dea80a2561107b6986

test:
  secret_key_base: faf5aeda2e6c2f414e18ecee9636acb2760ea2b84757bd78c95f73f2b79278a91922ab1e50b51c30c3201aad7973af131715ae175d646fc2da4f4dc28afe4a93

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
